sudo: false
language: node_js

matrix:
  include:
  - node_js: stable
    env: CXX=g++-4.8

script:
  - npm run lint

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
